services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"  

  ws-server:
    build:
      context: ./ws
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8080:8080" 

  go-engine:
    build:
      context: ./go_engine
      dockerfile: Dockerfile
    depends_on:
      - redis
      - ws-server
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379

  express-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - redis
      - go-engine
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000" 
