version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  ws-server:
    image: siddjuugi/probo_ws_server:latest
    container_name: ws-server
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8080:8080"

  engine:
    image: siddjuugi/probo_engine:latest
    container_name: engine
    depends_on:
      - redis
      - ws-server
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379

  express-server:
    image: siddjuugi/probo_exp_server:latest
    container_name: express-server
    depends_on:
      - redis
      - engine
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000" 
