apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-apps-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - probo.sidd.live
    - test.sidd.live
    - blog.sidd.live
    secretName: quickstart-example-tls
  rules:
  - host: probo.sidd.live
    http:
      paths:
      - path: /server(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: server-service
            port:
              number: 3000
      - path: /socket(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: ws-service
            port:
              number: 8080

  - host: test.sidd.live
    http:
      paths:
      - path: /chain(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: fast-chain-service
            port:
              number: 3005
      - path: /test(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: fast-server-service
            port:
              number: 8000

  - host: blog.sidd.live
    http:
      paths:
      - path: /app(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: blog-server-service
            port:
              number: 3010
