name: CI/CD Pipeline
on:
  push:
    branches:
    - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker server
      uses: docker/build-push-action@v4
      with:
        context: ./backend/go_engine
        push: true
        tags: |
          siddjuugi/probo_go_engine:latest 
          siddjuugi/probo_go_engine:${{ github.sha }}

    - name: Build and push Docker engine
      uses: docker/build-push-action@v4
      with:
        context: ./backend/ws
        push: true
        tags: |
          siddjuugi/probo_ws_server:latest 
          siddjuugi/probo_ws_server:${{ github.sha }}

    - name: Build and push Docker ws
      uses: docker/build-push-action@v4
      with:
        context: ./backend/server
        push: true
        tags: |
          siddjuugi/probo_exp_server:latest 
          siddjuugi/probo_exp_server:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Kubectl
      uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Update deployment images
      run: |
        kubectl set image deployment/server express-server=siddjuugi/probo_exp_server:${{ github.sha }}
        kubectl set image deployment/go-engine go-engine=siddjuugi/probo_go_engine:${{ github.sha }}
        kubectl set image deployment/ws-server go-ws=siddjuugi/probo_ws_server:${{ github.sha }}

    - name: Verify deployment for server
      run: |
        kubectl rollout status deployment/server

    - name: Verify deployment for go-engine
      run: |
        kubectl rollout status deployment/go-engine

    - name: Verify deployment for ws-server
      run: |
        kubectl rollout status deployment/ws-server
